### ISSUE TITLE
php.ini

### ISSUE THREAD

**Issue by andresgutierrez** [ndeet/pete#2]
Can you please post the php.ini and phpinfo(), maybe more tunning can be made there

**Comment by ndeet** [comment]
Hi,

thanks for bringing this up. 

For PHP 5.6 I used the one installed by default from Debian 8.2 php5-fpm package. For PHP 7 I copied the sample `php.ini-production` from the build directory (after compiling it).

I put the php.ini + phpinfo() output into the [configs/common](https://github.com/ndeet/pete/tree/master/configs/common) directory.

**Comment by ndeet** [comment]
Hi again, saw that you are ~~very active~~ the creator of Phalcon. Thanks for building such a fast framework. I was really amazed how fast it is compared to even Phoenix which is compiled. Do you think that Phalcon + PHP 7 will bring speed improvements like we see for Slim or because it is written in C the gains may not be that big compared to PHP 5.6?

**Comment by andresgutierrez** [comment]
I expect that PHP7 speeds up Phalcon even more :). Not sure how much, but probably between the range of 5% and 20%. I saw that ZendOptimizer+ is enabled in both PHP7 and PHP 5.6 so that's fine.

**Comment by andresgutierrez** [comment]
The following changes could speed up a bit the benchmark 

``` ini
opcache.revalidate_freq = 300
opcache.enable_file_override = On
```

**Comment by ndeet** [comment]
ad PHP 7: 
Great, will monitor your releases and give it a shot to compare it with the other results :+1: 

ad OPcache options:
Ok thanks a lot, will spin up the raspi and 12 core vm tomorrow and see how it performs.

**Comment by ndeet** [comment]
Awesome, re-run the PHP tests and results have improved by 10 - 20%, for Slim on 12-core even by > 40% with your tweaks. Updated the config section and php.ini too.

Let's see if we can make Phoenix use all system ressources and challange Phalcon at the top. Hopefully some Erlang/Elixir/Phoenix devs can take a look and hint what needs to be done :)

Thanks a lot @andresgutierrez
